micronaut:
  application:
    name: microtest

datasources:
  default:
    url: jdbc:mariadb://localhost:3306/test
    driverClassName: org.mariadb.jdbc.Driver
    username: root
    password: root
    dialect: MYSQL
jpa:
  default:
    packages-to-scan:
      - com.test.micronaut